mysite/first_page/urls.py
from django.urls import path
from . import views

app_name = 'first_page'
urlpatterns = [
    path('', views.show_page, name='show_page'),
    path('<int:page>', views.show_page, name='show_page'),
    path('load_more/<int:page>', views.load_more, name='load_more'),
    path('must_login', views.must_login, name='must_login'),
    path('info/', views.info, name='info'),
    path('signin', views.signin, name='signin'),
    path('signup', views.signup, name='signup'),
    path('signout', views.signout, name='signout'),
    path('new_task', views.new_task, name='new_task'),
    path('assign_task/<int:tid>', views.assign_task, name='assign_task'),
]

mysite/first_page/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.forms import ModelForm, ValidationError
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class Task(models.Model): 
	user = models.ForeignKey(User, default=None, null=True, on_delete=models.SET_DEFAULT)
	name = models.CharField(max_length=50)
	owner =	models.CharField(default=None, null=True, max_length=50)
	price = models.IntegerField()
	deadline = models.DateField()
	details = models.TextField(default='کارگذار هیچ توضیحی برای این کار اضافه نکرده است')

	def get_deadline(self):
		d = datetime.date.today()
		return (self.deadline-d).days

	def __str__(self):
		return self.name

class FormTask(ModelForm):
	class Meta:
		model = Task
		fields = ['name', 'price', 'deadline', 'details']
		labels = {
			'name': 'عنوان',
			'price': 'قیمت',
			'deadline': 'توضیحات',
			'details': 'زمان تخمینی',
		}
		error_messages = {
			'name': {'invalid':'مقدار وارد شده نامعتبر است', 'required':'پر کردن این فیلد اجباری است'},
			'price': {'invalid':'مقدار وارد شده نامعتبر است', 'required':'پر کردن این فیلد اجباری است'},
			'deadline': {'invalid':'مقدار وارد شده نامعتبر است', 'required':'پر کردن این فیلد اجباری است'},
			'details': {'invalid':'مقدار وارد شده نامعتبر است', 'required':'پر کردن این فیلد اجباری است'},
		}

	def clean_price(self):
		super().clean()
		price = self.cleaned_data['price']
		if price < 1000 or price > 50000:
			raise ValidationError('قیمت باید عددی بین ۱۰۰۰ تا ۵۰۰۰۰ باشد')
		return price

	def clean(self):
		super().clean()
		price = self.cleaned_data.get('price', None)
		date = self.cleaned_data.get('deadline', None)
		if not date or not price:
			return

		d = datetime.date.today()
		if (date-d).days <= 3 and price > 30000:
			raise ValidationError('حداکثر قیمت کار‌های با زمان ۳ روز ۳۰۰۰۰ تومان می باشد')

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	is_master = models.BooleanField(default=False)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
	instance.profile.save()

mysite/first_page/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator
from django.contrib.auth import login, authenticate, logout
from django.views.decorators.cache import cache_page
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Task, FormTask
from account_activation.views import send_activation_mail
import json
from functools import wraps
from datetime import datetime

class page_error:
    signin_error_text = []
    signup_error_text = []
    signup_succes_text = []
    must_login_error = False

    def clear(self):
        self.signup_error_text.clear()
        self.signin_error_text.clear()
        self.signup_succes_text.clear()
        must_login_error = False    

perror = page_error()

def master_only(func):
    @wraps(func)
    def wrap(request, *args, **kwargs):
        if request.user.profile.is_master is False:
            return HttpResponse("برای دسترسی به این بخش باید کارگذار باشید.")
        return func(request, *args, **kwargs)
    
    return wrap

def must_login(request):
    perror.must_login_error = True
    return HttpResponseRedirect(reverse('first_page:show_page'))

#@cache_page(60 * 4, cache='default')
def show_page(request, page=None):
    p = Paginator(Task.objects.all(), 4)

    if page != None:
        if p.num_pages < page:
            page = 1
        if page < 1:
            page = p.num_pages 
        request.session['page'] = page

    page = request.session.get('page', 1)
    page_list = range(1, p.num_pages+1)
    context = {
            'page': page,
            'page_list': page_list, 
            'num_page': p.num_pages, 
            'task': p.page(page).object_list,
            'page_error': perror,
            'User': request.user,
    }
    ret = render(request, 'first_page/index.html', context)
    perror.clear()
    return ret

def load_more(request, page):
    task = Paginator(Task.objects.all(), 4).page(page).object_list
    data = list()
    for t in task:
        data.append({'name': t.name,
                     'price': t.price,
                     'deadline': t.deadline.strftime("%b, %d, %Y"),
                     'owner': t.owner,
                     'id': t.id,
                     })
    return HttpResponse(json.dumps(data), content_type="application/json")



@login_required(login_url='first_page:must_login')
#@cache_page(60 * 4, cache='default')
def info(request):
    id = request.GET.get("id")
    if not id:
        raise Http404()

    task = Task.objects.get(pk=id)
    context = {'task': task, 'User': request.user}
    return render(request, 'first_page/details.html', context)

@login_required(login_url='first_page')
@master_only
def new_task(request):
    if not request.POST:
        form = FormTask()
        return render(request, 'first_page/new_task.html', {'User': request.user, 'form': form})
    form = FormTask(request.POST)
    if form.is_valid():
        task = form.save(commit=False)
        task.owner = request.user.username
        task.save()
        return HttpResponseRedirect(reverse('first_page:show_page'))
    else:
        return render(request, 'first_page/new_task.html', {'User': request.user, 'form': form})

@login_required(login_url='first_page')
def assign_task(request, tid):
    task = Task.objects.get(pk=tid)
    task.user = request.user
    task.save()
    return HttpResponseRedirect(reverse('first_page:info')+f'?id={tid}')

def signin(request):
    user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
    if user is not None and user.is_active:
        login(request, user)
    if not user.is_active:
        perror.signin_error_text.append('اکانت وارد شده فعال نشده است. برای فعال سازی به ایمیل خود مراجعه کنید')
    if user is None:
        perror.signin_error_text.append('رمز عبور یا نام کاربری صحیح نمیباشد')
    return HttpResponseRedirect(reverse('first_page:show_page'))

def signup(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    password_rpt = request.POST.get('password_rpt')
    email = request.POST.get('email')
    if request.POST.get('master')=='on':
        is_master = True
    else:
        is_master = False
    correct = True
    if not username or not password or not password_rpt or not email:
        correct = False
        perror.signup_error_text.append('فیلد های ضروری را پر کنید')
    if password != password_rpt:
        correct = False
        perror.signup_error_text.append('رمز عبور و تکرار رمز عبور یکسان نیست')
    if User.objects.filter(username=username).count() > 0:
        correct = False
        perror.signup_error_text.append('نام کاربری وارد شده قبلا استفاده شده است')   
    if correct:
        user = User.objects.create_user(username=username, password=password, email=email)
        # user.master = master(user=user, is_master=is_master)
        user.profile.is_master = is_master
        user.is_active = False
        user.save()
        send_activation_mail(request, user)
        perror.signup_succes_text.append('ثبت نام شما با موفقیت اناجم شد. لطفا ایمیل خود را تایید کنید.')
    return HttpResponseRedirect(reverse('first_page:show_page'))
        
def signout(request):
    logout(request)
    return HttpResponseRedirect(reverse('first_page:show_page'))

mysite/first_page/templates/first_page/details.html
<!DOCTYPE html>
<html lang="fa">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'first_page/bootstrap.min.css' %}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'first_page/main.css' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div id="main-content" class="col-md-9">
            <h1> سامانه‌ی انجام کار</h1>
            <div>
                <div class="col-sm-12">
                    {% if task.user is None %}
                    <a href="{% url 'first_page:assign_task' task.pk %}" class="btn btn-default">انجام می‌دم</a>
                    {% else %}
                    <p>
                        این کار توسط کاربر {{task.user.username}} در حال انجام است.
                    </p>
                    {% endif %}
                    <hr/>
                </div>
                <div class="col-sm-2"></div>
                <div class="col-sm-4">ساخته شده در {{task.deadline}}</div>
                <div class="col-sm-3">تومان {{task.price}}</div>
                <div class="col-sm-3">زمان باقی مانده {{ task.get_deadline }} روز</div>
                <div class="col-sm-12">
                    <br/>
                    توضیحات:
                    <br/>
                    {{task.details}}
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <p>
                شما با نام کاربری {{User.username}} به عنوان {% if User.profile.is_master %} کارگذار {% else %} کارمند {% endif %} وارد سیستم شده اید
            </p>
            <p style="text-align: center;">
                <a class="btn btn-default btn-block" href="{% url 'first_page:show_page' %}">صفحه‌ی اصلی</a>
                <a href="{% url 'first_page:signout' %}" class="btn btn-default btn-block">خروج</a>
            </p>
        </div>
    </div>
    <footer>
        <hr/>
        <span>درباه‌ی ما</span>
        <span>قوانین</span>
    </footer>
</div>
</body>
</html>

mysite/first_page/templates/first_page/index.html
<!DOCTYPE html>
<html lang="fa">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'first_page/bootstrap.min.css' %}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'first_page/main.css' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div id="main-content" class="col-md-9">
            <h1> سامانه‌ی انجام کار</h1>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>عنوان کار</th>
                    <th>ارزش کار</th>
                    <th>تخمین زمانی</th>
                    <th>صاحب کار</th>
                    <th>توضیحات</th>
                </tr>
                </thead>
                <tbody id="task_table">
                    {% for t in task %}
                        <tr>
                        <td>{{ t.name }}</td>
                        <td>{{ t.price }}</td>
                        <td>{{ t.deadline }}</td>
                        <td>{{ t.owner }}</td>
                        <td><a href="{% url 'first_page:info'%}?id={{t.id}}" class="btn btn-default">توضیحات بیشتر</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <p style="text-align: center;"><button id="next_page" class="btn-default">بیشتر</button>
        </div>
        <div class="col-md-3">
            {% if not User.is_authenticated %}
            <h3> ورود </h3>
            <form action="{% url 'first_page:signin' %}" method="post">
            {% csrf_token %}
                <fieldset>
                    <div class="form-group">
                        <input type="username" class="form-control" name="username" placeholder="نام کاربری">
                    </div>
                    <div>
                        <input type="password" class="form-control" name="password" placeholder="رمزعبور">
                    </div>
                </fieldset>
                <br>
                <input type="submit" value="ورود" class="btn btn-default btn-block">
                {% for error in page_error.signin_error_text %}
                    <p style="color: tomato;">*{{error}}</p>
                {% endfor %}
            </form>
            <hr/>
            <h3>ثبت نام</h3>
            <form action="{% url 'first_page:signup' %}" method="post">
            {% csrf_token %}
                <fieldset>
                    <div class="form-group">
                        <input name="username" maxlength="100" class="form-control" placeholder="نام‌کاربری">
                    </div>
                    <div class="form-group">
                        <input name="email" class="form-control" placeholder="ایمیل" type="email">
                    </div>
                    <div class="form-group">
                        <input name="password" class="form-control" placeholder="رمزعبور" type="password">
                    </div>
                    <div class="form-group">
                        <input name="password_rpt" class="form-control" placeholder="تکرار رمز عبور" type="password">
                    </div>
                    <div class="form-group">
                        <label><input name="master" type="checkbox">کارفرما</label>
                    </div>
                </fieldset>
                <input type="submit" value="ثبت نام" class="btn btn-default btn-block">
                {% for error in page_error.signup_error_text %}
                    <p style="color: tomato;">*{{error}}</p>
                {% endfor %}
                {% for succes in page_error.signup_succes_text %}
                    <p style="color: green;">#{{succes}}</p>
                {% endfor %}
            </form>
            {% else %}
            <p>
                شما با نام کاربری {{User.username}} به عنوان {% if User.profile.is_master %} کارگذار {% else %} کارمند {% endif %} وارد سیستم شده اید
            </p>
            <p style="text-align: center;"><a href="{% url 'first_page:new_task' %}" class="btn btn-default">اضافه کردن کار</a></p>
            <p style="text-align: center;"><a href="{% url 'first_page:signout' %}" class="btn btn-default">خروج</a></p>
            {% endif %}
        </div>
    </div>
    <footer>
        <hr/>
        <span> درباه‌ی ما</span>
        <span>قوانین</span>
        {% if page_error.must_login_error %}
        <style>
            .alert {
              padding: 20px;
              background-color: #f44336;
              color: white;
            }

            .closebtn {
              margin-left: 15px;
              color: white;
              font-weight: bold;
              float: right;
              font-size: 22px;
              line-height: 20px;
              cursor: pointer;
              transition: 0.3s;
            }

            .closebtn:hover {
              color: black;
            }
            </style>
        <div class="alert">
            <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
            برای دسترسی به این بخش باید وارد اکانت خود شوید.
        </div> 
        {% endif %}
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        $(document).ready(function() {
            var page = 2;
            $("#next_page").click(function(){
                $.get("load_more/"+page, 
                function(data, status){
                    data.forEach(function(t){
                        var html = `
                        <tr>
                            <td>${t.name}</td>
                            <td>${t.price}</td>
                            <td>${t.deadline}</td>
                            <td>${t.owner}</td>
                            <td><a href="{% url 'first_page:info' %}?id=${t.id}" class="btn btn-default">توضیحات بیشتر</a></td>
                        </tr>`
                        $("#task_table").append(html);
                    });
                    page = page+1;
                }, "json");
                if(page >= {{num_page}}){
                    var x = document.getElementById("next_page")
                    x.style.display = "none";
                }
            });
        });
    </script>

</div>
</body>
</html>

mysite/first_page/templates/first_page/new_task.html
<!DOCTYPE html>
<html lang="fa">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'first_page/bootstrap.min.css' %}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'first_page/main.css' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div id="main-content" class="col-md-9">
            <h1> سامانه‌ی انجام کار</h1>
            <div>
                <h3> افزودن کار جدید </h3>
                <form action="{% url 'first_page:new_task' %}" method="post" class="form-horizontal">
                {% csrf_token %}
                    <div class="form-group">
                        <div class="col-sm-4"></div>
                        <div class="col-sm-6">
                            <input name="name" class="form-control" maxlength="250">
                        </div>
                        <label class="control-label col-sm-2" for="name">عنوان</label>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-4"></div>
                        <div class="col-sm-6">
                            <textarea name="details" class="form-control" cols="40" rows="10"></textarea>
                        </div>
                        <label class="control-label col-sm-2" for="details">توضیحات</label>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-4"></div>
                        <div class="col-sm-6">
                            <input name="price" class="form-control" type="number">
                        </div>
                        <label class="control-label col-sm-2" for="price">قیمت</label>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-4"></div>
                        <div class="col-sm-6">
                            <input name="deadline" class="form-control" type="date">
                        </div>
                        <label class="control-label col-sm-2" for="deadline">زمان تخمینی</label>
                    </div>
                    <div class="col-sm-4"></div>
                    <div class="col-sm-8">
                        <input type=submit value="افزودن کار" class="btn btn-default btn-block">
                        {% if form.errors %}
                    <div class="alert alert-danger">
                        {{ form.errors }}
                    </div>
                {% endif %}
                    </div>
                    <br><br>
                    
                </form>

            </div>
        </div>
        <div class="col-md-3">
            <p>
                شما با نام کاربری {{User.username}} به عنوان {% if User.profile.is_master %} کارگذار {% else %} کارمند {% endif %} وارد سیستم شده اید
            </p>
            <p style="text-align: center;">
                <a class="btn btn-default btn-block" href="{% url 'first_page:show_page' %}">صفحه‌ی اصلی</a>
                <a href="{% url 'first_page:signout' %}" class="btn btn-default btn-block">خروج</a>
            </p>
        </div>
    </div>
    <footer>
        <hr/>
        <span> درباه‌ی ما</span>
        <span>قوانین</span>
    </footer>
</div>
</body>
</html>