mysite - Old template/first_page/urls.py
from django.urls import path
from . import views

app_name = 'first_page'
urlpatterns = [
    path('', views.show_page, name='show_page'),
    path('<int:page>', views.show_page, name='show_page_num'),
    path('info/<int:id>', views.info, name='info'),
]

mysite - Old template/hello/urls.py
from django.urls import path
from django.http import HttpResponse
from . import views

urlpatterns = [
    path('<str:name>', views.say),
    path('', views.say),
]

mysite - Old template/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('first_page/', include('first_page.urls')),
    path('hello/', include('hello.urls')),
    path('search/', include('search.urls')),
]

mysite - Old template/search/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.search),
    path('<str:query>', views.search),
]

mysite - Old template/Employee_model/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    work = models.CharField(max_length=100)

    def __str__(self):
        return sel.work
    

mysite - Old template/first_page/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime

# Create your models here.
class Task(models.Model):
	name = models.CharField(max_length=50)
	deadline = models.DateField()
	price = models.IntegerField()
	user = models.CharField(max_length=50)

	def get_deadline(self):
		d = datetime.date.today()
		return (d-self.deadline)

	def __str__(self):
		return self.name

mysite - Old template/hello/models.py
from django.db import models

# Create your models here.

mysite - Old template/search/models.py
from django.db import models

# Create your models here.

mysite - Old template/Employee_model/views.py
from django.shortcuts import render

# Create your views here.

mysite - Old template/first_page/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.core.paginator import Paginator
from .models import Task 
num_of_page = 0

def show_page(request, page=None):
    p = Paginator(Task.objects.all(), 5)

    if page != None:
        if p.num_pages < page:
            page = 1
        if page < 1:
            page = p.num_pages 
        request.session['page'] = page

    page = request.session.get('page', 1)
    context = {'page': page, 'num_page': p.num_pages, 'task': p.page(page).object_list}
    return render(request, 'first_page/index.html', context)

def info(request, id):
    task = Task.objects.get(pk=id)
    context = {'task': task}
    return render(request, 'first_page/info.html', context)
    

mysite - Old template/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def say(request, name=None):
    if(name == None):
        return HttpResponse('ooops\n you did not enter any name')
    return HttpResponse('SALAM {}'.format(name))

mysite - Old template/search/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
import os

# Create your views here.
def search(request, query=None):
    # index = open('search/template/index.html', 'w')
    # index.write('<h1>You did not enter any word</h1>')
    # index.close()
    if(query == None):query = request.GET.get('Query', None)
    if(query == None):
        return HttpResponse('You did not enter any word')
    return redirect('https://www.google.com/search?channel=fs&client=ubuntu&q={}'.format(query))

mysite - Old template/first_page/templates/first_page/index.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="index.css">
    </head>

    <style>
        table, th, td{
          border:1px solid black;
          text-align: center;
        }

        table {
          width: 100%;
          border-collapse: collapse;
        }

        th {
          height: 60px;
          background-color: SlateBlue;
          color: white;
        }

        td {
          height: 40px;
        }

        .button1 {
          border: none;
          color: white;
          padding: 16px 32px;
          text-align: center;
          text-decoration: none;
          display: inline-block;
          font-size: 16px;
          margin: 4px 2px;
          transition-duration: 0.4s;
          cursor: pointer;
          background-color: white; 
          color: black; 
          border: 2px solid #4CAF50;
        }

        .button1:hover {
          background-color: #4CAF50;
          color: white;
        }

        .button2 {
          border: none;
          color: white;
          padding: 16px 32px;
          text-align: center;
          text-decoration: none;
          display: inline-block;
          font-size: 16px;
          margin: 4px 2px;
          transition-duration: 0.4s;
          cursor: pointer;
          background-color: white; 
          color: black; 
          border: 2px solid #008CBA;
        }

        .button2:hover {
          background-color: #008CBA;
          color: white;
        }

        .button3 {
          border: none;
          color: white;
          padding: 16px 32px;
          text-align: center;
          text-decoration: none;
          display: inline-block;
          font-size: 16px;
          margin: 4px 2px;
          transition-duration: 0.4s;
          cursor: pointer;
          background-color: white; 
          color: black; 
          border: 2px solid purple;
        }

        .button3:hover {
          background-color: purple;
          color: white;
        }
        .w3-right{float:right!important}

        tr:nth-child(even) {background-color: Gold;}
        tr:nth-child(odd) {background-color: GoldenRod;} 

    </style>

    <body>
    <h1 style="text-align: center;">Work organization system</h1>
    <table class="width100%">
        <tr>
            <th>Title</th> 
            <th>Price</th>
            <th>Deadline</th> 
            <th>Master</th>
            <th>Info</th>
        </tr>
        {% for t in task %}
        <tr>
            <td>{{ t.name }}</td>
            <td>{{ t.price }}</td>
            <td>{{ t.deadline }}</td>
            <td>{{ t.user }}</td>
            <td><button onclick="location.href='{% url 'first_page:info' t.id %}'">show</button></td>
        </tr>
        {% endfor %}
    </table>
    <p style="text-align: center;">
        <button class="button2">Privacy policy</button>
        <button class="button3" onclick="location.href='{% url 'first_page:show_page_num' page|add:'-1' %}'" ><<<</button>
        <button class="button3" onclick="location.href='{% url 'first_page:show_page_num' page|add:'+1' %}'" >>>></button>
        <button class="button1">About us</button>
    </p>
    <p style="text-align: center;">Page {{ page }} of {{ num_page }}</p>
    </body>
    
</html>

mysite - Old template/first_page/templates/first_page/info.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="index.css">
    </head>
    <style>
        .button3 {
          border: none;
          color: white;
          padding: 16px 32px;
          text-align: center;
          text-decoration: none;
          display: inline-block;
          font-size: 16px;
          margin: 4px 2px;
          transition-duration: 0.4s;
          cursor: pointer;
          background-color: white; 
          color: black; 
          border: 2px solid purple;
        }

        .button3:hover {
          background-color: purple;
          color: white;
        }

        p {text-align: center;}
    </style>
    <body>
        <h1 style="text-align: center;">Task information page</h1>
        <hr style="width:50%;text-align:center;">
        <p>Showing information for task: {{ task.name }}</p>
        <p>Owner of this task: {{ task.user }}</p>
        <p>Time left to arrive deadline: {{ task.get_deadline }}</p>
        <p><button class="button3" onclick="location.href='{% url 'first_page:show_page' %}'">Back</button></p>
    </body>
</html>